#!/usr/bin/env bash
# Refresh tests/schema/pleb_api.sql from pleb-api's migrations (pleb-api owns the schema).
# Usage: scripts/sync-schema.sh [path-to-pleb-api]   (default ../pleb-api)
set -euo pipefail
api="${1:-../pleb-api}"
src="$api/internal/db/migrations"
out="$(dirname "$0")/../tests/schema/pleb_api.sql"
[ -d "$src" ] || { echo "no migrations at $src" >&2; exit 1; }
{
  echo "-- Generated by scripts/sync-schema.sh from pleb-api's migrations. Do not edit."
  for f in "$src"/*.sql; do
    echo "-- source: $(basename "$f") sha256:$(sha256sum "$f" | cut -d' ' -f1)"
  done
  for f in "$src"/*.sql; do
    sed -n '/^-- +goose Up/,/^-- +goose Down/p' "$f" | sed '/^-- +goose/d'
  done
} > "$out"
echo "wrote $out"
